name: Test Golang SDK library

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run unit tests
        run: make tests
